name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.20', '1.19']
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      GOPROXY: ''
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: go/src/github.com/go-extras/websocket

      - name: Print the Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run golint
        if: matrix.go-version == '1.20'
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run gofmt
        if: matrix.go-version == '1.20'
        run: diff -u <(echo -n) <(gofmt -d -e .)

      - name: Run go vet
        if: matrix.go-version == '1.20'
        run: go vet -v ./...

      - name: Run go test (+ race detector)
        run: go test -v -race ./...
